makeOurPlanetGreenAgain/makeOurPlanetGreenAgain/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plateforme.urls')),
    path('projets/', include('projet.urls'))
]

makeOurPlanetGreenAgain/plateforme/urls.py
from django.urls import path
from . import views
from .feeds import ProjectsFeed

app_name = "plateforme"
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('credits/', views.credits, name='credits'),
    path('auth/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('register/', views.register_view, name='register_view'),
    path('latest/feed/', ProjectsFeed(), name='rss_view'),
    path('add_to_cart/', views.cookie_add_to_cart, name='add_to_cart'),
    path('remove_from_cart/', views.cookie_remove_from_cart, name='remove_from_cart'),
    path('checkout/',views.checkout_view,name="checkout_view"),
    path('checkout_fund/',views.checkout_fund,name="checkout_fund"),
    path('search/', views.search, name='search'),
    path('search_users/', views.search_user, name='search_users'),
    path('profile/', views.profile, name='profile_view')
]

makeOurPlanetGreenAgain/projet/urls.py
from django.urls import path
from . import views

app_name = 'projet'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:project_id>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),
    path('validate/<int:project_id>/', views.validate, name='validate')
]

makeOurPlanetGreenAgain/projet/models.py
from django.db import models
from django.contrib.auth.models import User
from copyright.models import Copyright
from datetime import datetime


class Projet(models.Model):
	nom = models.CharField(max_length=20)
	membres = models.ManyToManyField(User)
	montant = models.IntegerField()
	financement = models.IntegerField(default=0)
	copyright = models.OneToOneField(Copyright, on_delete=models.CASCADE, blank=True, default=None, null=True)
	publication_date = models.DateTimeField(default=datetime.now)
	description = models.CharField(max_length=1000)

makeOurPlanetGreenAgain/projet/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Projet


class ProjectForm(forms.ModelForm):
    nom = forms.CharField(required=True)
    # TODO ajout membres
    #membres = forms.ModelMultipleChoiceField(queryset=User.objects.all())
    montant = forms.IntegerField(required=True)
    description = forms.CharField(required=True)
    # TODO ajout copyright

    class Meta:
        model = Projet
        fields = ["nom", "montant", "description"]
        widgets = {
            'description': forms.Textarea()
        }

makeOurPlanetGreenAgain/projet/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import F
from django.contrib import messages
from .models import Projet
from .forms import ProjectForm
from expert.models import Expert
from plateforme.models import Commentaire
from plateforme.forms import CommentForm
import logging
from django.contrib.auth.models import User

log = logging.getLogger(__name__)


def index(request):
    # on affiche les projets qui n'ont pas été complètement financés
    project_list = Projet.objects.filter(financement__lt=F("montant")).order_by('-publication_date')

    paginator = Paginator(project_list, 6)  # 6 projets par page
    page = request.GET.get('page')

    try:
        projects = paginator.page(page)
    except PageNotAnInteger:
        projects = paginator.page(1)
    except EmptyPage:
        projects = paginator.page(paginator.num_pages)

    context = {'projects': projects}
    return render(request, "projet/index.html", context)


def detail(request, project_id):
    project = get_object_or_404(Projet, pk=project_id)
    comments = Commentaire.objects.filter(projet__exact=project).order_by('-publication_date')

    context = {'project': project, 'comments': comments}

    # check if project is validated by experts
    if project.expert_set.exists():
        experts = project.expert_set.all().order_by('-karma')
        context['experts'] = experts
    # check if the actual user is an expert
    if request.user.is_authenticated and Expert.objects.filter(utilisateur__exact=request.user).exists():
        context['user_can_validate'] = True

    if request.method == 'GET':
        form = CommentForm()
    else:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.utilisateur = request.user
            comment.projet = project
            comment.save()
            return redirect('projet:detail', project_id=project_id)

    context['form'] = form
    return render(request, "projet/detail.html", context)


def add(request):

    if request.method == 'GET':
        form = ProjectForm()
    else:
        form = ProjectForm(request.POST)
        if form.is_valid():
            log.error(request.POST)
            cpt=0
            for key in request.POST:
                if '_item' in key:
                    cpt+=1
            if cpt >0 :
                form.save()
                p= Projet.objects.get(nom=request.POST['nom'])

                if p :
                    for key in request.POST:
                        if'_item' in key:
                            p.membres.add(User.objects.get(username=request.POST[key]))
                            p.save()
            else :
                return render(request, "projet/add.html" ,{"error" : "Missing members field"})
        else:
            return render(request, "projet/add.html", {"error": form.errors})

        return redirect('projet:index')

    return render(request, "projet/add.html", {'form': form})


def validate(request, project_id):
    validated_project = get_object_or_404(Projet, pk=project_id)
    expert = Expert.objects.get(utilisateur=request.user)

    # Check if expert has already validated the project
    if Expert.objects.filter(validated_projects__pk=project_id).exists():
        messages.info(request, 'Vous avez déjà validé ce projet !')
    else:
        expert.validated_projects.add(validated_project)
        expert.save()

    return redirect('projet:detail', project_id=project_id)

makeOurPlanetGreenAgain/projet/templates/projet/add.html
{% extends "base.html" %}

{% block content %}
<style>
.my-custom-scrollbar {
position: relative;
height: 200px;
overflow: auto;
}
.table-wrapper-scroll-y {
display: block;
}
</style>
<h1 class="my-3">Nouveau projet</h1>
<script>

    $(document).on('click','.user-row',function(e) {

        if($("#users-list").children("#"+$(this).find("#username_d").text()+"_row").text()==""){

             $("#users-list").append("<tr id="+$(this).find("#username_d").text()+"_row>" +
            "        <td> <input type=\"hidden\" name='"+$(this).find("#username_d").text()+"_item' value='"+$(this).find("#username_d").text()+"' />"+$(this).find("#username_d").text()+"</td>" +
            "        <td> <button class='remove_user btn btn-danger' type='button'><strong>x</strong></button </td>" +
            "      </tr>")
        }

    });

    $(document).on('click','.remove_user',function(e) {

        $($($(this).parent()).parent()).remove()
    })
</script>


<form class="form" action="" role="form" method="post" id="project_form">
    {% csrf_token %}
    <div class="form-group">
        <input id="nameInput" name="nom" placeholder="Project name" class="form-control form-control-sm" type="text"
               required="">
    </div>
    <div class="form-group">
        <textarea id="descriptinoArea" name="description" placeholder="Description" class="form-control form-control-sm"
                  required=""></textarea>
    </div>
    <div class="form-group">
        <input id="montantInput" name="montant" placeholder="Montant" class="form-control form-control-sm" type="number"
               required="">
    </div>
    {% load static %}

        <div>
            <input id="search-input-user" class="form-control" placeholder="Search">
        </div>
        <div id="users-div">
            {% include 'plateforme/users-results.html' %}
        </div>
<div class="table-wrapper-scroll-y my-custom-scrollbar mb-2 bg-light " style="text-align: center">

<script type="text/javascript" src="{% static 'js/search_users.js' %}"></script>

  <table class="table table-bordered table-striped mb-0">
    <thead>
      <tr>
        <th scope="col">Username</th>
          <th scope="col"></th>
      </tr>
    </thead>
    <tbody id="users-list">

    </tbody>
  </table>
    {% if error %}
    <p class="text-danger"><strong>{{ error }}</strong></p>
    {% endif %}
</div>

    <div class="form-group">
        <input type="submit" class="btn btn-primary btn-block" value="Submit"/>
    </div>
</form>


{% endblock %}

makeOurPlanetGreenAgain/projet/templates/projet/detail.html
{% extends "base.html" %}

{% block content %}
{% load staticfiles %}

    <script>


      $(document).on('click','#cart',function(e) {

          var isInCart = new Boolean(false)

          $("#cartList").children().each(function(i) {

              if ($($($(this).children("td")[0]).children("a")[0]).text() == "{{ project.nom }}"){
                  isInCart=true
              }
            });

            if(isInCart==false){

                var lineCart = {"projectName" : "{{  project.nom }}", "projectPath": this.baseURI }

                console.log(JSON.stringify(lineCart))
                $.ajax({
                    type: "POST",
                    beforeSend: function(request) {
                        request.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                    },
                    url: '{% url "plateforme:add_to_cart" %}',
                    dataType: "json",
                    data: {"list" :lineCart},
                      success: function () {
                        console.log("success")

                           $("#cartList").append(
                '             <tr id="'+"{{  project.nom }}"+'_cart_row">\n' +
                '              <th scope="row">'+($("#cartList").children().length)+'</th>\n' +
                '              <td> <a href="'+this.baseURI+'">{{ project.nom }}</a></td>\n' +
                '              <td> <button id="{{ project.nom }}_cart" class=" button-cart-remove btn btn-outline-secondary btn-danger text-light">X</button></td>\n' +

                '            </tr>')

                      },
                      error: function (data) {
                        alert("Impossible d'ajouter au panier.")
                      },
                      complete: function (data) {
                      }
                    })
            }else{
                alert("Impossible d'ajouter au panier. Projet déjà présent !")
            }
        });


    </script>

{% if messages %}
    <script>
    {% for message in messages %}
        alert("{{ message }}");
    {% endfor %}
    </script>
{% endif %}


<div class="container mt-3">
    <h1>{{ project.nom }}</h1>
    <small>Published on {{ project.publication_date|date:"F d, Y" }}</small>
    <hr>
<div class="my-3">
        <small>Funds raised</small>
        <div class="progress">
            {% widthratio project.financement project.montant 100 as width%}
            <div class="progress-bar" style="width:{{ width }}%">{{ width }}%</div>
        </div>
    </div>
    <hr>

    <div class="row mt-5 ">
        {% if project.montant > project.financement %}
        <div class="col" style="text-align: right">
             {% if user.is_authenticated %}
            {% load static %}
            <button id="cart" type="button" class="btn btn-info text-white" data-toggle="modal" data-target="#modalCart">
                Add to cart ? <img src="{% static 'img/cart.png' %}" width="20" />
            </button>
            {% endif %}
        </div>
      {% endif %}
    </div>

    <div class="row mt-3 mb-5">
        <div class="col-sm">
            <p class="lead">{{ project.description }}</p>
            <small><img src="{% static 'img/copyright_logo.png' %}">
                {{ project.copyright.nom }}</small>
        </div>
        <div class="col-3">
            <p class="lead">Amount : {{ project.montant }} €</p>
            <hr>
            <p>Members :</p>
            {% for membre in project.membres.all %}
            <p class="ml-3">{{ membre.first_name }} {{ membre.last_name }}</p>
            {% endfor %}

            {% if experts %}
                <hr>
                <p>Validated by :</p>
                {% for expert in experts %}
                <p class="ml-3">{{ expert.utilisateur.first_name }} {{ expert.utilisateur.last_name }}</p>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    {% if user_can_validate %}
    <div class="row justify-content-center mb-5">
        <form action="{% url 'projet:validate' project_id=project.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Validate project</button>
        </form>
    </div>
    {% endif %}

    <hr>
    <div class="mt-4">
        <p class="font-weight-light">Comments :</p>
         {% if user.is_authenticated %}
        <form class="form" action="" role="form" method="post">
            {% csrf_token %}
            <div class="form-group">
                <textarea id="contentInput" name="content" placeholder="Comment" class="form-control form-control-sm"
                       required=""></textarea>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary btn-block" value="Submit"/>
            </div>
        </form>
        {% endif %}
    </div>
    <div class="list-group mb-3">
        {% for comment in comments %}
        <div class="list-group-item">
            <div class="d-flex justify-content-between">
                <h5 class="mb-1">{{ comment.utilisateur.first_name }} {{ comment.utilisateur.last_name }} :</h5>
                <small>{{ comment.publication_date|date:"d F Y, G:i" }}</small>
            </div>
            <p class="mb-1 pr-5">{{ comment.content|linebreaksbr }}</p>
        </div>
        {% endfor %}
    </div>


</div>
</div>


{% endblock %}

makeOurPlanetGreenAgain/projet/templates/projet/index.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col my-3">
        <h1>Projects under funding</h1>
    </div>
   {% if user.is_authenticated %}
    <div class="col-2 my-4">
        <a href="{% url 'projet:add' %}" class="btn btn-primary">Add project</a>
    </div>
    {% endif %}
</div>

{% if projects %}
<div class="list-group mx-4">
    {% for project in projects %}
    <a href="{% url 'projet:detail' project.id %}" class="list-group-item list-group-item-action">
        <div class="d-flex justify-content-between">
            <h5 class="mb-1">{{ project.nom }}</h5>
            <small>{{ project.publication_date|date:"d F Y" }}</small>
        </div>
        <p class="mb-1 pr-5">{{ project.description|truncatewords_html:50 }}</p>
        <small>Amount : {{ project.montant }} €</small>
    </a>

    {% endfor %}
</div>
{% else %}
<p class="lead">There is no project yet. Add one !</p>
{% endif %}

<div class="m-4">
{% if projects.has_other_pages %}
    <nav aria-label="Pagination">
        <ul class="pagination">
            {% if projects.has_previous %}
            <li class="page-item"><a href="?page={{ projects.previous_page_number }}" class="page-link">Previous</a></li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">Previous</span></li>
            {% endif %}
            {% for i in projects.paginator.page_range %}
                {% if projects.number == i %}
                <li class="page-item active"><span class="page-link">{{ i }}</span></li>
                {% else %}
                <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if projects.has_next %}
            <li class="page-item"><a href="?page={{ projects.next_page_number }}" class="page-link">Next</a></li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">Next</span></li>
            {% endif %}
        </ul>
    </nav>
{% endif %}
</div>

{% endblock %}