makeOurPlanetGreenAgain/makeOurPlanetGreenAgain/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plateforme.urls')),
    path('projets/', include('projet.urls'))
]

makeOurPlanetGreenAgain/plateforme/urls.py
from django.urls import path
from . import views
from .feeds import ProjectsFeed

app_name = "plateforme"
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('credits/', views.credits, name='credits'),
    path('auth/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('register/', views.register_view, name='register_view'),
    path('latest/feed/', ProjectsFeed(), name='rss_view'),
    path('add_to_cart/', views.cookie_add_to_cart, name='add_to_cart'),
    path('remove_from_cart/', views.cookie_remove_from_cart, name='remove_from_cart'),
    path('checkout/',views.checkout_view,name="checkout_view"),
    path('checkout_fund/',views.checkout_fund,name="checkout_fund"),
    path('search/', views.search, name='search'),
    path('search_users/', views.search_user, name='search_users'),
    path('profile/', views.profile, name='profile_view')
]

makeOurPlanetGreenAgain/projet/urls.py
from django.urls import path
from . import views

app_name = 'projet'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:project_id>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),
    path('validate/<int:project_id>/', views.validate, name='validate')
]

makeOurPlanetGreenAgain/templates/base.html
{# block used as header #}
{% block header %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Make our planet green again</title>

    <script
            src="https://code.jquery.com/jquery-3.4.1.js"
            integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
            crossorigin="anonymous"></script>

    {% load static %}
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    {% load static %}
    <script src="{% static 'js/bootstrap.js' %}"></script>


</head>
{% endblock %}
<body>
{% block nav %}
<script>

 function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}


</script>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top" role="navigation">
    <div class="container">
        <a class="navbar-brand" href="/">GreenAgain</a>
        <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
            &#9776;
        </button>
        <div class="collapse navbar-collapse" id="exCollapsingNavbar">
            <ul class="nav navbar-nav">
                <li class="nav-item"><a href="{% url 'plateforme:index'%}" class="nav-link">Homepage</a></li>
                <li class="nav-item"><a href="{% url 'projet:index'%}" class="nav-link">Projects list</a></li>
                <li class="nav-item"><a href="{% url 'plateforme:contact'%}" class="nav-link">Contact</a></li>
                <li class="nav-item"><a href="{% url 'plateforme:search'%}" class="nav-link">Search</a></li>
                <li class="nav-item"><a href="{% url 'plateforme:credits'%}" class="nav-link">Legal</a></li>
            </ul>
            <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
                <li class="nav-item order-2 order-md-1"><a href="#" class="nav-link" title="settings"><i
                        class="fa fa-cog fa-fw fa-lg"></i></a></li>

                {% if user.is_authenticated %}
                <li class=" order-1">
                    <form class="form" role="form" method="post" action="/logout/">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-secondary btn-danger text-light">Logout</button>
                    </form>
                </li>
                <li class=" order-1">
                    <form class="form" role="form" method="post" action="/profile/?page=1">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-secondary btn-info text-light">
                            <img src="{% static 'img/profile.png' %}" width="20"/>
                        </button>
                    </form>
                </li>
                <li class="order-sm-3">
                    {% load static %}
                    <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modalCart">
                        <img src="{% static 'img/cart.png' %}" width="20"/>
                    </button>
                </li>

                {% else %}
                <li class="dropdown order-1">
                    <button type="button" id="dropdownMenu1" data-toggle="dropdown"
                            class="btn btn-outline-secondary dropdown-toggle btn-success text-light">Login <span
                            class="caret"></span></button>
                    <ul class="dropdown-menu dropdown-menu-right mt-2">
                        <li class="px-3 py-2">
                            <form class="form" role="form" method="post" action="/auth/">
                                <div class="form-group">
                                    <input id="emailInput" name="username" placeholder="Email"
                                           class="form-control form-control-sm" type="text" required="">
                                </div>
                                <div class="form-group">
                                    <input id="passwordInput" type="password" name="password" placeholder="Password"
                                           class="form-control form-control-sm" type="text" required="">
                                </div>
                                <div class="form-group">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary btn-block">Login</button>
                                </div>
                                <div class="form-group text-center">
                                    <small><a href="#" data-toggle="modal" data-target="#modalPassword">Forgot
                                        password?</a></small>
                                </div>
                            </form>
                        </li>
                    </ul>

                </li>
                <li class="pl-1 ">
                    <form class="form" role="form" method="get" action="/register/">
                        <button type="submit" class="btn btn-outline-secondary btn-info text-light">Sign in</button>
                    </form>
                </li>

                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div id="modalPassword" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3>Forgot password</h3>
                <button type="button" class="close font-weight-light" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <p>Reset your password..</p>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                <button class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal: modalCart -->
<div class="modal fade" id="modalCart" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <!--Header-->
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Your project(s) cart : </h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <!--Body-->
            <div class="modal-body">

                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Project name</th>
                        <th>Remove</th>
                    </tr>
                    </thead>
                    <tbody id="cartList">
                    {% load marktags %}

                    <script>
                var list_p= new String("{{request.COOKIES.cart_projects }}").replace(/\&#39;/g,"\"")
                if(list_p){
                     var js=JSON.parse(list_p)

                jQuery.each(js["list"], function() {

                    $("#cartList").append(
                '            <tr id="'+this[0]+'_cart_row">\n' +
                '              <th scope="row">'+($("#cartList").children().length)+'</th>\n' +
                '              <td> <a href="'+this[1]+'">'+this[0]+'</a></td>\n' +
                '              <td> <button id="'+this[0]+'_cart" class=" button-cart-remove btn btn-outline-secondary btn-danger text-light">X</button></td>\n' +
                '            </tr>')

                   })
                }


            $(document).on('click','.button-cart-remove',function(e) {
                $("#"+this.id+"_row").fadeOut()
                $("#"+this.id+"_row").remove()
                $.ajax({
                    type: "POST",
                    beforeSend: function(request) {
                        request.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                    },
                    url: '{% url "plateforme:remove_from_cart" %}',
                    dataType: "json",
                    data: {"name" :this.id},
                      success: function () {

                      },
                      error: function () {
                        alert("Impossible d'ajouter au panier.")
                      },
                      complete: function (data) {
                      }
                    })


            })


                    </script>
                    <p></p>

                    </tbody>
                </table>

            </div>
            <!--Footer-->
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Close</button>
                <form class="form" role="form" method="post" action="/checkout/">
                    {% csrf_token %}
                    <button class="btn btn-primary">Checkout</button>
                </form>

            </div>
        </div>
    </div>
</div>

{% endblock %}
<div class="container-fluid">
    {% block content %}
    {% endblock %}
</div>
{% block footer%}
<footer>
</footer>
</body>
</html>
{% endblock %}

makeOurPlanetGreenAgain/templates/email.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title></title>
    <style>
			@import url('https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900');

    </style>
</head>
<body style="background: #f5f8fa;font-family: 'Roboto', sans-serif;">
<div style="width: 90%;max-width:600px;margin: 20px auto;background: #ffffff;">
    <section style="margin: 0 15px;color:#425b76;">
        <h2 style="margin: 40px 0 27px 0;text-align: center;">Thank you to registration</h2>
        <hr style="border:0;border-top: 1px solid rgba(66,91,118,0.3);max-width: 50%">
        <p style="font-size:15.5px;font-weight: bold;margin:40px 20px 15px 20px;">Hi {{username}}, we have received your
            details and will process soon.</p>
    </section>
</div>
</body>
</html>