makeOurPlanetGreenAgain/makeOurPlanetGreenAgain/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plateforme.urls')),
    path('projets/', include('projet.urls'))
]

makeOurPlanetGreenAgain/plateforme/urls.py
from django.urls import path
from . import views
from .feeds import ProjectsFeed

app_name = "plateforme"
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('credits/', views.credits, name='credits'),
    path('auth/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('register/', views.register_view, name='register_view'),
    path('latest/feed/', ProjectsFeed(), name='rss_view'),
    path('add_to_cart/', views.cookie_add_to_cart, name='add_to_cart'),
    path('remove_from_cart/', views.cookie_remove_from_cart, name='remove_from_cart'),
    path('checkout/',views.checkout_view,name="checkout_view"),
    path('checkout_fund/',views.checkout_fund,name="checkout_fund"),
    path('search/', views.search, name='search'),
    path('search_users/', views.search_user, name='search_users'),
    path('profile/', views.profile, name='profile_view')
]

makeOurPlanetGreenAgain/projet/urls.py
from django.urls import path
from . import views

app_name = 'projet'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:project_id>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),
    path('validate/<int:project_id>/', views.validate, name='validate')
]

makeOurPlanetGreenAgain/plateforme/models.py
from django.contrib.auth.models import User
from django.db import models
from projet.models import Projet
from datetime import datetime


class Commentaire(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    content = models.CharField(max_length=2500)
    projet = models.ForeignKey(Projet, on_delete=models.CASCADE)
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)
    publication_date = models.DateTimeField(default=datetime.now)

makeOurPlanetGreenAgain/plateforme/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Commentaire


class LoginForm(forms.Form):
    username = forms.CharField(label='username', max_length=100)
    password = forms.CharField(label='password', max_length=100)


class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(label="first_name",max_length=20)
    last_name = forms.CharField(label="last_name",max_length=20)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name']


class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    mail = forms.EmailField(required=True)
    subject = forms.CharField(required=False)
    message = forms.CharField(required=True, widget=forms.Textarea)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Commentaire
        fields = ['content']
        widgets = {
            'content': forms.Textarea()
        }

makeOurPlanetGreenAgain/plateforme/views.py
import datetime
import json
import logging

from django.db.models import QuerySet
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from expert.models import Expert
from makeOurPlanetGreenAgain import settings
from .models import User
from . import forms as f
from django.core.mail import send_mail, BadHeaderError
from .forms import ContactForm
from projet.models import Projet
from financeurs.models import financeur, Paiement
from .models import Commentaire
from django.template.loader import render_to_string
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from itertools import chain

log = logging.getLogger(__name__)


def index(request):
    random_project_list = Projet.objects.order_by('?')[:5]
    context = {'random_project_list': random_project_list}
    if request.user.is_authenticated:
        last_projects = financeur.objects.filter(utilisateur=request.user)
        paiement = Paiement.objects.order_by("date_paiement").filter(id_user=request.user.id)

        if paiement.count() > 0:
            comments = Commentaire.objects.filter(projet=paiement.last().projet)[:5]
            context = {'random_project_list': random_project_list, "user_last_project": paiement.last().projet,
                       "num_project": last_projects[0].projetsfinances.all().count(), "comments_project": comments,
                       "num_paiment": paiement.count()}
    return render(request, "plateforme/index.html", context)


def profile(request):
    paiements = Paiement.objects.order_by("date_paiement").filter(id_user=request.user.id)
    paginator = Paginator(paiements, 8)  # 8 projets par page





    page = request.GET.get('page')

    try:
        paiements = paginator.page(page)
    except PageNotAnInteger:
        paiements = paginator.page(1)
    except EmptyPage:
        paiements = paginator.page(paginator.num_pages)
    if Expert.objects.filter(utilisateur=request.user):
        expert = Expert.objects.get(utilisateur=request.user)
        context = {"paiements": paiements, "validated_projects": expert.validated_projects.all()}
    else:
        context = {"paiements": paiements}

    return render(request, "plateforme/profile.html", context)


def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)

        if form.is_valid():
            name = form.cleaned_data['name']
            mail = form.cleaned_data['mail']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']

            try:
                send_mail(
                    subject,
                    message,
                    mail,
                    ['makeourplanetgreetagain@example.fr']
                )
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('/contact/')

    return render(request, "plateforme/contact.html", {'form': form})


def credits(request):
    return render(request, "plateforme/credits.html")


def login_view(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = f.LoginForm(request.POST)

        # check whether it's valid:
        if form.is_valid():
            username = form['username'].value()
            password = form['password'].value()
            user = authenticate(request, username=username, password=password)

            if user is not None:
                log.error("authenticated")
                login(request, user)
            else:
                log.error("failed")

            return redirect('/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = f.LoginForm()

    return render(request, 'plateforme/index.html')


def logout_view(request):
    logout(request)
    return redirect('/')


def register_view(request):
    if request.method == 'POST':
        form = f.RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password2')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                log.error("authenticated")
                login(request, user)

            ######################### mail system ####################################
            # htmly = get_template('email.html')
            # d = {'username': 'username'}
            # subject, from_email, to = 'welcome', 'planetgreenagain@outlook.com', 'fernandez27.tf@gmail.com'
            # html_content = htmly.render(d)
            # msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
            # msg.attach_alternative(html_content, "text / html")
            # msg.send()
            return redirect('/')
        else:
            log.error(form.error_messages)
            return render(request, 'plateforme/register.html', {'form': form, 'data': request.POST})

    else:
        form = f.RegisterForm()

    return render(request, 'plateforme/register.html')


def checkout_view(request):
    value = request.COOKIES.get('cart_projects')

    list = ""
    if value != None:

        cookieToDict = json.loads(value.replace('\'', '\"'))

        list = cookieToDict['list']

        result = Projet.objects.none()

        for item in list:
            p = Projet.objects.filter(nom=item['0'])
            result = chain(result, p)

    context = {'cart': result}

    return render(request, "plateforme/checkout.html", context)


def search_dict(d, ksearch):
    for v in d:  # for name, age in dictionary.iteritems():  (for Python 2.x)
        if v["id"] == ksearch:
            return v["amount"]
    return 0


def checkout_fund(request):
    fundsToDict = json.loads(request.POST["data"])

    user = request.user

    cart = request.COOKIES.get('cart_projects')

    cookieToDict = json.loads(cart.replace('\'', '\"'))

    list = cookieToDict['list']

    financeur.objects.get_or_create(utilisateur=user)
    f = financeur.objects.get(utilisateur=user)
    paiementList = []

    for item in list:
        datep = datetime.datetime.now()
        Paiement.objects.create(id_user=user.id, date_paiement=datep,
                                projet=Projet.objects.get(nom=item['0']),
                                montant=int(search_dict(fundsToDict, str(item['0']) + "_fund")))
        paiementList.append({
            "date_paiement": datep.__str__(),
            "project_name": item['0'],
            "montant": int(search_dict(fundsToDict, str(item['0']) + "_fund"))
        })

        old_financement = int(Projet.objects.filter(nom=item['0'])[0].financement)

        new_financement = (int(search_dict(fundsToDict, str(item['0']) + "_fund"))) + old_financement

        Projet.objects.filter(nom=item['0']).update(financement=new_financement)
        f.projetsfinances.add(Projet.objects.get(nom=item['0']))
        f.save()

    json_data = json.dumps({"HTTPRESPONSE": "ok", "paiements": paiementList})
    response = HttpResponse(json_data, content_type="application/json")
    return response


def set_cookie(response, key, value, days_expire=7):
    if days_expire is None:
        max_age = 365 * 24 * 60 * 60  # one year
    else:
        max_age = days_expire * 24 * 60 * 60
    expires = datetime.datetime.strftime(datetime.datetime.utcnow() + datetime.timedelta(seconds=max_age),
                                         "%a, %d-%b-%Y %H:%M:%S GMT")
    response.set_cookie(key, value, max_age=max_age, expires=expires, secure=None)


def cookie_add_to_cart(request):
    projectName = request.POST["list[projectName]"]
    projectPath = request.POST["list[projectPath]"]

    json_data = json.dumps({"HTTPRESPONSE": "ok"})
    response = HttpResponse(json_data, content_type="application/json")

    value = request.COOKIES.get('cart_projects')

    if value != None:
        log.error(value)
        cookieToDict = json.loads(value.replace('\'', '\"'))

        list = cookieToDict['list']
        list.append({'0': projectName, '1': projectPath})

        cookieToDict["list"] = list
        value = cookieToDict

    else:
        value = {"list": [{"0": projectName, "1": projectPath}]}

    set_cookie(response, "cart_projects", json.loads(json.dumps(value)))

    return response


def cookie_remove_from_cart(request):
    projectName = request.POST["name"].replace("_cart", "")

    value = request.COOKIES.get('cart_projects')
    if value != None:
        cookieToDict = json.loads(value.replace('\'', '\"'))
        list = cookieToDict['list']
        toRemove = ""

        for i in list:
            if i['0'] == projectName:
                toRemove = i
        if toRemove != "":
            list.remove(toRemove)

        cookieToDict['list'] = list

        value = cookieToDict

    json_data = json.dumps({"HTTPRESPONSE": "ok"})
    response = HttpResponse(json_data, content_type="application/json")

    set_cookie(response, "cart_projects", json.loads(json.dumps(value)))

    return response


def search(request):
    url_parameter = request.GET.get("q")

    if url_parameter:
        project_list = Projet.objects.filter(nom__icontains=url_parameter).order_by('-publication_date')
    else:
        project_list = Projet.objects.all().order_by('-publication_date')

    paginator = Paginator(project_list, 6)  # 6 projets par page
    page = request.GET.get('page')

    try:
        projects = paginator.page(page)
    except PageNotAnInteger:
        projects = paginator.page(1)
    except EmptyPage:
        projects = paginator.page(paginator.num_pages)

    context = {'projects': projects}

    if request.is_ajax():
        html = render_to_string(

makeOurPlanetGreenAgain/plateforme/templates/plateforme/checkout.html
{% extends "base.html" %}

{% block content %}

<script>
        $(document).on('change','input',function() {

                 if(this.value > parseInt(this.max)){
                     this.value=this.max
                 }
            });

        $(document).on('click','#btnCheckoutbefore',function(e) {
            $('#recapBeforeCheckout').empty()
             if($(".list_checkout").children().length <=0){

                  $('#recapBeforeCheckout').append(" <li class=\"list-group-item\">Basket is empty !!!</li>")
                  $('#btnCheckout').hide()
             }
             else{

            $(".list_checkout").children().each(function () {
                $('#recapBeforeCheckout').append(" <li class=\"list-group-item\">" +
                                  "<br> <strong>Project name : </strong> "+$(this).find(".projectName").text()+" " +
                                  "<br> <strong>Amount : </strong> "+$(this).find("input").val()+" € " +
                                  "</li>")
            })

                  $('#btnCheckout').show()
             }


            $('#validPaiement').modal('show');


             })

        $(document).on('click','.button-checkout-remove',function(e) {

               $.ajax({
                    type: "POST",
                    beforeSend: function(request) {
                        request.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                    },
                    url: '{% url "plateforme:remove_from_cart" %}',
                    dataType: "json",
                    data: {"name" :this.id},
                      success: function () {

                      },
                      error: function () {
                        alert("Impossible d'ajouter au panier.")
                      },
                      complete: function (data) {

                      }
                    })

                $("#"+this.id+"_row").remove()
                $("#"+this.id+"_checkout").fadeOut()
                $("#"+this.id+"_checkout").remove()

                if($(".list_checkout").children().length ==0){
                    $(".card").append('<p class="lead ml-2">There is no project in your basket. <a href="{% url "projet:index" %}">Finance one !</a></p>')
                }
            })

         $(document).on('click','#btnCheckout',function(e) {



              if($(".list_checkout").children().length >0){

                  funds =$(".list_checkout").find(".fund")

                  data =[]

                  for (i=0;i<funds.length;i++){
                      data.push({ "id" : funds[i].id, "amount" : funds[i].value });
                  }

                   $.ajax({
                        type: "POST",
                        beforeSend: function(request) {
                            request.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                        },
                        url: '{% url "plateforme:checkout_fund" %}',
                        dataType: "json",
                        data: {"data" : JSON.stringify(data) },
                          success: function (data) {

                              $( ".button-checkout-remove" ).each(function( index ) {
                                 this.click()
                                });
                              $('#successPaiement').modal('show');
                              data["paiements"].forEach(element =>  $('#recapCheckout').append(" <li class=\"list-group-item\"><strong>Date de paiement : </strong> "+element["date_paiement"]+"" +
                                  "<br> <strong>Project name: </strong> "+element["project_name"]+" " +
                                  "<br> <strong>Amount : </strong> "+element["montant"]+" € " +
                                  "</li>"))
                          },
                          error: function () {
                            console.log("error")
                              alert("Payment not completed")
                          },
                          complete: function (data) {

                          }
                    })
              }

         })
</script>

<div class="card mt-2">
    <div class="card-header mb-2"><h2> Cart projects : </h2></div>

    {% if cart %}
    <div class="list_checkout mx-4 my-2 " style="text-align: right">
        {% for item in cart %}
        <div id="{{item.nom}}_cart_checkout">
            <button id="{{ item.nom }}_cart"
                    class="button-checkout-remove btn btn-outline-secondary btn-danger text-light ml-5 mb-2">
                <strong>X</strong></button>
            <a href="{% url 'projet:detail' item.id %}" class="list-group-item list-group-item-action"
               style="text-align: left">
                <div class="d-flex justify-content-between ">
                    <h5 class="mb-1 projectName">{{ item.nom }}</h5>
                    <small> Publication date : {{ item.publication_date|date:"d F Y" }}
                    </small>
                </div>
                <p class="mb-1 pr-5">{{ item.description|truncatewords_html:50 }}</p>
                <small>Amount : {{ item.montant }} €</small>
            </a>
            <div class="row">

                <div class="input-group mb-3 col-12 d-flex justify-content-end mt-3 ">
                    {% load marktags %}
                    <div class="d-flex justify-content-end mt-2 mr-5"><strong>Max amount : </strong> {% subtractify item %} <strong>€</strong></div>
                    <div class="input-group-prepend ">
                        <span class="input-group-text border-info ">€</span>
                    </div>
                    <input id="{{ item.nom }}_fund" type="number" min="1" max="{% subtractify item %}" value=1
                           class="fund border   border-info" style="text-align: right; width:20%">
                    <div class="input-group-append">
                        <span class="input-group-text border-info"> </span>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p class="lead ml-2 mt-3">There is no project in your basket. <a href="{% url 'projet:index' %}">Finance one !</a>
    </p>
    {% endif %}
</div>

<div class="container-fluid" style="text-align: center">
    <button id="btnCheckoutbefore" class="btn btn-outline-success w-25 mt-3" type="button">Checkout !</button>
</div>


<div id="successPaiement" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><strong>Panier vidé !</strong></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Recap : </p>
                <ul id="recapCheckout" class="list-group">

                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">Thank you !</button>
            </div>
        </div>
    </div>
</div>

<div id="validPaiement" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><strong>Confirm your purchase : </strong></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Recap : </p>
                <ul id="recapBeforeCheckout" class="list-group">
                </ul>
            </div>
            <div class="modal-footer">
                <button id="btnCheckout" type="button" class="btn btn-success" data-dismiss="modal">Pay !</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Go back</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

makeOurPlanetGreenAgain/plateforme/templates/plateforme/credits.html
{% extends "base.html" %}

{% block content %}

<div class="container mt-3">
    <h1>Crédits et mentions légales</h1>
    <ul class="mt-4">
        <li><strong>Editeur :</strong>
            <ul>
                <li>Elaboration technique : Poirier Romane, Fernandez Thierry</li>
                <li>Création graphique : Poirier Romane, Fernandez Thierry</li>
            </ul>
        </li><br>
        <li>
            <strong>Droits d'auteurs et copyright :</strong><br>
            L'ensemble de ce site relève de la législation française et internationale sur le droit d'auteur et la
            propriété intellectuelle. Tous les droits de reproduction sont réservés, y compris pour les documents
            téléchargeables et les représentations iconographiques et photographiques.<br>
            La reproduction de tout ou partie de ce site sur un support électronique quel qu'il soit est formellement
            interdite sauf autorisation expresse du directeur de la publication.
        </li>
    </ul>
</div>

{% endblock %}

makeOurPlanetGreenAgain/plateforme/templates/plateforme/index.html
{% extends "base.html" %}

{% block content %}


<script>
      $(document).on('click','.project',function(e) {
            document.location.href = "/projets/"+this.id+"/"
        });


</script>
{% load static %}

<div class="text-center">
    <a href="{%url 'plateforme:rss_view' %}" height="42" width="42" style="display: inline-block">
        <img src="{% static 'img/rss-feed.png' %}" height="42" width="42" class="rounded mx-auto d-block mt-2"/>
    </a>
</div>
{% if user.is_authenticated %}
<div class="text-center mt-2 lead">
    <p class=""> Hello <strong>{{ user.username }}</strong> you have contributed to
        <strong>{{num_project|default:'0'}}</strong> project(s) with <strong>{{num_paiment|default:'0'}}</strong>
        paiements .</p>
</div>


<div class="card mt-2">
    <div class="card-header"><h2> Last projects funded : </h2></div>
    <div class="card-body">

        {% if user_last_project %}

        <a href="{% url 'projet:detail' user_last_project.id %}"
           class=" border-dark list-group-item list-group-item-action" style="border-width:3px">
            <div id="{{ user_last_project.id }}" class="d-flex justify-content-between ">
                <h5 class="mb-1">{{ user_last_project.nom }}</h5>

                <div><small>{{ user_last_project.publication_date|date:"d F Y" }}</small>
                    {% if user_last_project.financement == user_last_project.montant %}
                    <span class="badge badge-success">Finished </span>
                    {% else %}
                    <span class="badge badge-warning">In progress</span>
                    {% endif %}
                </div>
            </div>
            <p class="mb-1 pr-5">{{ user_last_project.description|truncatewords_html:50 }}</p>
            <small>Amount : {{ user_last_project.montant }} €</small>
        </a>

        {% if comments_project %}
        <div class="card-body"> Comment(s) :</div>
        {% for comment in comments_project %}
        <p class="ml-4"><strong>{{ comment.utilisateur.username }}</strong> : {{ comment.content }} </p>
        {% endfor %}
        {% else %}
        <div class="card-body"> No comments.</div>
        {% endif %}

        {% else %}
        No project funded.
        {% endif %}
    </div>
</div>
{% else %}
<div class="card mt-2">
    <div class="card-header">Create an account / connect to your account ! for more content !</div>
</div>
{% endif %}


<div class="card mt-2">
    <div class="card-header mb-2"><h2> Random projects : </h2></div>

    {% if random_project_list %}
    <div class=" mx-4 my-2">
        {% for random_project in random_project_list %}
        <a href="{% url 'projet:detail' random_project.id %}" class="list-group-item list-group-item-action">
            <div class="d-flex justify-content-between ">
                <h5 class="mb-1">{{ random_project.nom }}</h5>

                <div><small>{{ random_project.publication_date|date:"d F Y" }}</small>
                    {% if random_project.financement == random_project.montant %}
                    <span class="badge badge-success">Finished </span>
                    {% else %}
                    <span class="badge badge-warning">In progress</span>
                    {% endif %}
                </div>
            </div>
            <p class="mb-1 pr-5">{{ random_project.description|truncatewords_html:50 }}</p>
            <small>Amount : {{ random_project.montant }} €</small>
        </a>
        {% endfor %}
    </div>
    {% else %}
    <p class="lead">There is no project yet. Add one !</p>
    {% endif %}

    {% comment %} {% if random_project_list %}
    {% for random_project in random_project_list %}
    <div id="{{ random_project.id }}" class=" project card border-dark mt-4 ml-4 mr-4 mb-1">
        <div class="card-header"><h2>{{ random_project.nom }} : </h2></div>
        <div class="card-body">{{ random_project.description }}</div>
    </div>
    {% endfor %}

    {% else %}
    <div class="card-body">no project now...</div>
    {% endif %}{% endcomment %}
</div>


{% endblock %}

makeOurPlanetGreenAgain/plateforme/templates/plateforme/profile.html
{% extends "base.html" %}

{% block content %}


<div class="row">
    <div class="col my-3">
        <h1>Payments history :</h1>


        {% if paiements %}
        <div class="list-group mx-4">
            {% for paiement in paiements %}
            <a href="{% url 'projet:detail' paiement.projet.id %}" class="list-group-item list-group-item-action">
                <div class="d-flex justify-content-between">
                    <h5 class="mb-1">{{ paiement.projet.nom }}</h5>
                    <small>Payment date : {{ paiement.date_paiement|date:"d F Y - h:m" }}</small>
                </div>
                <small>Payed : {{ paiement.montant }} €</small>
            </a>
            {% endfor %}
        </div>
        {% else %}
        <p class="lead">You have no payment yet.</p>
        {% endif %}

        <div class="m-4">
            {% if paiements.has_other_pages %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if paiements.has_previous %}
                    <li class="page-item"><a href="?page={{ paiements.previous_page_number }}" class="page-link">Previous</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled"><span class="page-link">Previous</span></li>
                    {% endif %}
                    {% for i in paiements.paginator.page_range %}
                    {% if projects.number == i %}
                    <li class="page-item active"><span class="page-link">{{ i }}</span></li>
                    {% else %}
                    <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if paiements.has_next %}
                    <li class="page-item"><a href="?page={{ paiements.next_page_number }}" class="page-link">Next</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled"><span class="page-link">Next</span></li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>

    </div>
    <div class="col-3 my-5">
        {% if validated_projects %}
        <p><strong>Validated projects :</strong></p>
        <div class="list-group">
            {% for project in validated_projects%}
            <a href="{% url 'projet:detail' project.id %}" class="list-group-item list-group-item-action">
                <div class="d-flex justify-content-between">
                    <p class="mb-1">{{ project.nom }}</p>
                </div>
            </a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

makeOurPlanetGreenAgain/plateforme/templates/plateforme/projects-results.html
{% if projects %}
<div class="list-group m-4">
    {% for project in projects %}
    <a href="{% url 'projet:detail' project.id %}" class="list-group-item list-group-item-action">
        <div class="d-flex justify-content-between">
            <h5 class="mb-1">{{ project.nom }}</h5>
            <small>{{ project.publication_date|date:"d F Y" }}</small>
        </div>
        <p class="mb-1 pr-5">{{ project.description|truncatewords_html:50 }}</p>
        <div class="d-flex justify-content-between">
            <small>Amount : {{ project.montant }} €</small>
            {% ifequal project.financement project.montant %}
            <span class="badge badge-success">Finished</span>
            {% else %}
            <span class="badge badge-warning">In progress</span>
            {% endifequal %}
        </div>
    </a>

    {% endfor %}
</div>
{% else %}
{% endif %}

<!-- TODO save q object in links -->
<div id="pagination-div" class="m-4">
    {% if projects.has_other_pages %}
    <nav aria-label="Pagination">
        <ul class="pagination">
            {% if projects.has_previous %}
            <li class="page-item"><a href="?page={{ projects.previous_page_number }}" class="page-link">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">Previous</span></li>
            {% endif %}
            {% for i in projects.paginator.page_range %}
            {% if projects.number == i %}
            <li class="page-item active"><span class="page-link">{{ i }}</span></li>
            {% else %}
            <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if projects.has_next %}
            <li class="page-item"><a href="?page={{ projects.next_page_number }}" class="page-link">Next</a></li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">Next</span></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>